name: Publish to GHPages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Create Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install and Build App
        run: |
          npm ci
          npm run build
      - name: Setup GH Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./dist/
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
  deploy:
    name: Deploy
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v2
